FROM superng6/nginx-with-cache-purge:latest

LABEL maintainer="NG6"

RUN addgroup -S www-data \
&&  adduser -D -S -h /var/www/html -s /sbin/nologin -G www-data www-data

COPY uploads.ini /usr/local/etc/php/conf.d/uploads.ini
COPY nginx-wp.conf /etc/nginx/nginx.conf
COPY default-wp.conf /etc/nginx/conf.d/default.conf